# Don't print a new line at the start of the prompt
add_newline = false

[directory]
truncation_length = 8
truncate_to_repo = false

# Takes a lot of time in large repositories (e.g. nixpkgs)
[git_status]
disabled = true
